version: "3.8"

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    networks:
      - app-network
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: ../frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next

networks:
  app-network:
    driver: bridge
